# Generated by Django 5.0.3 on 2024-03-18 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ["-timestamp"]},
        ),
    ]
