# Generated by Django 5.0.3 on 2024-03-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_movie_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="idx",
            field=models.IntegerField(
                blank=True, help_text="Position ids for ml", null=True
            ),
        ),
    ]
